# Python & NumPy Tutorial

En este tutorial nos centraremos en entender algunas cosas básicas de Python 3 junto con algunas de las librerias (paquetes) más usadas hoy en día para Inteligencia Artificial (IA)


Algo mas de introduccion aca supongo

# Python 3

De no estar familiarizado con Python 3 y sus diferencias con Python 2 aqui te mostramos algunas

### Print 

In [1]:
print("¡Hola Mundo!")

¡Hola Mundo!


In [2]:
print "¡Hola Error!"

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("¡Hola Error!")? (<ipython-input-2-af0fd51bc4e3>, line 1)

### No hay xrange

Lo que se conocia como xrange() en Python 2 ahora se conoce como range() en Python 3. En Python 3 range() no crea una 
lista de elementos como lo sería en Python 2, sino que crea un elemento iterativo con mejor uso de memoria.

In [3]:
range(3)

range(0, 3)

In [4]:
for i in range(3):
    print(i)

0
1
2


In [5]:
print(list(range(3)))

[0, 1, 2]


Hablemos ahora de algunas cosas basicas de Python:

In [6]:
x = 5
y = 5

Python tiene varias funciones ya integreadas que, a pesar de hacer mas facil varios calculos, pueden confundir si no se tiene claro que tipo de resultado devuelve cada una. Por ejemplo:

In [7]:
x == y

True

"is" compara valor y tipo.

In [8]:
x is y

True

In [9]:
x**y

3125

Importante anotar: En Python, "**" es el operador para elevar x a la y. "^" es un operador binario XOR.

In [10]:
x^(y-1)

1

In [11]:
5/2

2.5

In [12]:
5//2

2

Ahora miremos las estructuras basicas

In [13]:
# Los condicionales
if (x != y):
    print("x no es igual a y")
else:
    print("son iguales")
        

son iguales


In [14]:
# and , or and not 
elementA = 4
elementB = 3
if(elementA == 4 and elementB == 3):
    print("En Python no hay & sino and")
if(elementA < 5 or elementB != 3):
    print("En Python no hay | sino or")
if not(elementA != 4):
    print("Que pasa aca?")

En Python no hay & sino and
En Python no hay | sino or
Que pasa aca?


En Python podemos crear un script a "fuerza bruta", por medio de funciones (metodo mas usual) y con clases (personas que saben lo que estan haciendo...)

In [15]:
c = 5*5
print(c)

25


In [16]:
def Multi(x,y):
    c = x*y
    return c
res = Multi(x,y)
print(res)

25


In [17]:
class MyClass:
    """A simple example class"""
    def Multi(self,x,y):
        c = x*y
        return c
A = MyClass()
res = A.Multi(x,y)
print(res)

25


In [18]:
pets=['dog','cat','ferret']
'fox' in pets

False

# NumPy

NumPy es una libreria (paquete) fundamental para todo lo relaciondo con ciencias de la computación en Python. 
Es una libreria de Python que proporciona un objeto de matriz multidimensional y una variedad de rutinas para operaciones rápidas en matrices, incluyendo matemática, lógica, manipulación de formas, clasificación y selecció, entre muchas otras.
- https://docs.scipy.org/doc/numpy/user/quickstart.html

In [19]:
import numpy as np

Ahora la pregunta es... ¿Que tan poderoso es NumPy en realidad?, vamos a hacer unos ejemplos

Supongamos que tenemos dos listas (a y b) con los primeros 100000 no negativos numeros enteros en cada una, 
y queremos crear una nueva lista que tenga cuya i-esima posición sea a[i] + 3*b[i]

Sin NumPy:

In [20]:
%%time
a = [i for i in range(100000)]
b = [i for i in range(100000)]

CPU times: user 14.7 ms, sys: 5.93 ms, total: 20.6 ms
Wall time: 19.9 ms


In [21]:
%%time
c = []
for i in range(len(a)):
    c.append(a[i] + 2 * b[i])

CPU times: user 54.3 ms, sys: 6.68 ms, total: 61 ms
Wall time: 64.1 ms


Con NumPy:

In [22]:
%%time
a = np.arange(100000)
b = np.arange(100000)

CPU times: user 4.53 ms, sys: 2.99 ms, total: 7.51 ms
Wall time: 5.54 ms


In [23]:
%%time
c = a + 2 * b

CPU times: user 4.26 ms, sys: 3.12 ms, total: 7.38 ms
Wall time: 6.07 ms


El resultado es mucho mas rapido con NumPy, y eso... aun asi se puede hacer con menos lineas de codigo

Python a "fuerza bruta" suele ser muy lento dado las validaciones constantes que tiene que realizar para llevar a cabo muchas operaciones (Por ejemplo, interpretar codigo y soportar la abstracción que tiene Python).
Para ponerlo mas en contexto, llevar a cabo una suma en un **PARA**, hace que se tenga que revisar el tipo de dato constantemente, lo cual tiene como consecuencia que se realicen muchas mas operaciones que una suma.

NumPy, usando codigos optimizados que estan pre-compilados en C es capaz de superar muchas de las dificultades antes mencionadas

El proceso que usamos con NumPy se conoce como **vectorización**. La vectorización hace referencia a realizar operaciones en arreglos (arrays) en vez de elementos individuales (Ejemplo de esto es no usar **PARA**)

Entonces, ¿Que ventajas tiene la vectorizacón?
- Mas rapido
- Menos lineas de codigo
- Mas orientado a la notación matematica
- Muchas mas

La vectorización es una de las razones por las que NumPy es tan fuerte.

In [24]:
%%time
results = []
for i in range(1000):
    for j in range(i):
        results.append((i, j))
        

CPU times: user 164 ms, sys: 25.3 ms, total: 189 ms
Wall time: 196 ms


In [25]:
%%time
results = []
results = [(i, j) for i in range(1000) for j in range(i)]


CPU times: user 86.3 ms, sys: 28.6 ms, total: 115 ms
Wall time: 113 ms


### n-dimensional arrays (ndarray)

Los ndarrays son arrays de tipo similiar los cuales son la base de NumPy. A pesar de que ofrecen menos flexibilidad que las usuales listas de Python ofrecen mejores tiempos de ejecucion y mejor uso de memoria.

In [26]:
a = np.array([1,2,3])    # Crea un array de dimensión 1
print(type(a))           # Muestra en pantalla "<class 'numpy.ndarray'>"
print(a.shape)           
print(a[0], a[2])
a[1] = 10
print(a)
print(" ")

b = np.array([[1, 2, 3],
              [4, 5, 6]])    # Crea un array de dimensión 2
print(b.shape)
print(b[0,0], b[1,0])

<class 'numpy.ndarray'>
(3,)
1 3
[ 1 10  3]
 
(2, 3)
1 4


Otras formas de inicializar arrays con NumPy

In [27]:
a = np.zeros((2,2) , dtype = int)
print(a)
b = np.full((2,2), 5, dtype = int)
print(b)
c = np.eye(2, dtype = int)
print(c)
d = np.ones((2,2), dtype = int)
print(d)

# Entre otras

[[0 0]
 [0 0]]
[[5 5]
 [5 5]]
[[1 0]
 [0 1]]
[[1 1]
 [1 1]]


¿Y si queremos jugar con una matriz?

In [28]:
array = np.arange(8)
print(array)
print(array.shape)

array = array.reshape((2,4))
print("reshaped : \n", array)
print(array.shape)

array = array.reshape((4,-1))
print("reshaped con -1: \n", array)
print(array.shape)

[0 1 2 3 4 5 6 7]
(8,)
reshaped : 
 [[0 1 2 3]
 [4 5 6 7]]
(2, 4)
reshaped con -1: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)


### Operaciones con ndarrays

Elemento a elemento:

In [29]:
arrayA = np.array([[1, 2],
                   [3, 4]], dtype = int)

arrayB = np.array([[5, 6],
                   [7, 8]], dtype = int)


# Suma Elemento a Elemento
print(arrayA + arrayB)
print(np.add(arrayA, arrayB))

# Resta Elemento a Elemento
print(arrayA - arrayB)
print(np.subtract(arrayA, arrayB))

# Multiplicacion Elemento a Elemento
print(arrayA * arrayB)
print(np.multiply(arrayA, arrayB))

# sqrt Elemento a Elemento
print(np.sqrt(arrayA))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


**OJO**, en el bloque de arriba estabamos hablando de operaciones elemento a elemento , no multiplicacio de vectores o matrices. Si queremos hacer multiplicaciones vector / vector, vector / matriz , matriz / matriz, podemos usar la función **dot** la cual existe en NumPy

In [30]:
arrayA = np.array([[1, 2],
                   [3, 4]])

arrayB = np.array([[5, 6],
                   [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# Producto interno entre vectores ( vector / vector)
print(v.dot(w))
print(np.dot(v, w))

# Producto de vector / matriz
print(v.dot(arrayA))
print(np.dot(v,arrayA))

# o viceversa
print(arrayA.dot(v))
print(np.dot(arrayA, v))

# Producto de matriz / matriz
print(arrayA.dot(arrayB))
print(np.dot(arrayA, arrayB))

219
219
[39 58]
[39 58]
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Tambien podemos realizar operaciones con una matriz

In [31]:
x = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8]])

print(np.sum(x))                # Computa la suma de todos los elementos de la matriz 
print(np.sum(x, axis = 0))      # Computa la suma de cada columna de la matriz 
print(np.sum(x, axis = 1))      # Computa la suma de cada fila de la matriz 

print(np.max(x))                # Halla el maximo elemento de la matriz

36
[ 6  8 10 12]
[10 26]
8


### Indexing

In [39]:
x = np.array([[1, 2, 3], 
              [4, 5, 6],
             [7, 8, 9]])

print("Original: \n", x)

# Podemos seleccioar el valor de cualquier posición del codigo

print("Posición [1][1] de x", x[1][1])
print("Posición [1, 1] de x", x[1, 1])

# Podemos usar : para seleccionar una subparte de la matriz
print("Posiciones [:2,:2] de x \n", x[:2,:2])

# Cosas extras
print("Invertir una fila  de la matrix(x[0, ::-1]) :\n ", x[0, ::-1])

Original: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Posición [1][1] de x 5
Posición [1, 1] de x 5
Posiciones [:2,:2] de x 
 [[1 2]
 [4 5]]
Invertir una fila  de la matrix(x[0, ::-1]) :
  [3 2 1]


A menudo puede que necesitemos modificar elementos de las filas o columnas de una matriz

In [44]:
arrayA = np.array([[1, 2, 3], 
                   [4, 5, 6],
                   [7, 8, 9]])
print("La matrix es: \n",arrayA)

# Creemos un array de indices
b = np.array([0,1,2])

# Seleccionaremos de cada fila un elemento de acuerdo a los indices de b
print("los valores son: \n", arrayA[np.arange(3), b])

# Modifiquemos ahora esos valores
arrayA[np.arange(3),b] +=1
print("La nueva matrix es: \n", arrayA)

La matrix es: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
los valores son: 
 [1 5 9]
La nueva matrix es: 
 [[ 2  2  3]
 [ 4  6  6]
 [ 7  8 10]]


Tambien podemos realizar comparaciones booleanas o comparaciones numericas

In [46]:
arrayA = np.array([[1, 2, 3], 
                   [4, 5, 6],
                   [7, 8, 9]])
temp = 5
print(temp > arrayA)
arrayA[temp > arrayA] += 1
print(arrayA)


[[ True  True  True]
 [ True False False]
 [False False False]]
[[2 3 4]
 [5 5 6]
 [7 8 9]]
